- name: UBUNTU18 | Add certbot repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7BF576066ADA65728FC7E70A8C47BE8E75BCA694
  tags:
    - certbot

- name: UBUNTU18 | Add repositories
  apt_repository:
    repo: "{{ item }}"
  loop:
    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_facts.lsb.codename }} universe'
    - 'deb http://ppa.launchpad.net/certbot/certbot/ubuntu {{ ansible_facts.lsb.codename }} main'
  tags:
    - certbot

- name: UBUNTU18 | Install certbot
  apt:
    name: "{{ certbot_packages }}"
    state: present
    update_cache: true
  tags:
    - certbot
