- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution != 'Ubuntu'
  tags:
    - certbot

- name: Include variables for Ubuntu
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - certbot

- include: "install-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution != 'Ubuntu'
  tags:
    - certbot

- include: "install-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - certbot

- name: Configure automatic renewal
  cron:
    cron_file: certbot
    user: root
    name: "{{ certbot_cron.name }}"
    job: "{{ certbot_cron.job }}"
    day: "{{ certbot_cron.day | default('*') }}"
    hour: "{{ certbot_cron.hour }}"
    minute: "{{ certbot_cron.minute | default('0') }}"
  tags:
    - certbot
    - certbot_cron
