- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
    - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.os_distribution }}.yml"
    - defaults/main.yml
  tags:
    - certbot

- name: Include installation tasks
  include_tasks: "{{ outer_item }}"
  with_first_found:
    - "install-{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "install-{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
    - "install-{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "install-{{ ansible_facts.os_family }}.yml"
    - "install-{{ ansible_facts.os_distribution }}.yml"
  loop_control:
    loop_var: outer_item
  tags:
    - certbot

- name: Configure automatic renewal
  cron:
    cron_file: certbot
    user: root
    name: "{{ certbot_cron.name }}"
    job: "{{ certbot_cron.job }}"
    day: "{{ certbot_cron.day | default('*') }}"
    hour: "{{ certbot_cron.hour }}"
    minute: "{{ certbot_cron.minute | default('0') }}"
  tags:
    - certbot
    - certbot_cron
